name: LDC_Test
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - jupyter
  - plotly
  - dash
  - pip
  - matplotlib
  - pip:
    - plotly-express
    - xgboost
    - scikit-learn
